name: Documentation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  markdown-check:
    name: Validate Markdown Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Markdown lint check
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            **/*.md
